name: Lint the java code

on: [push, pull_request]
    # push:
    #     branches:
    #         - main
    #         - develop
    # pull_request:
    #     branches:
    #         - main
    #         - develop 

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code 
              uses: actions/checkout@v3

            - name: setup jdk 
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'
            
            - name: Install checkstyle
              run: |
                  sudo apt-get install checkstyle
                  sudo apt-get install unzip
                  wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3/checkstyle-10.3-all.jar
                  

            - name: Run checkstyle
              run: java -jar checkstyle-10.3-all.jar -c /google_checks.xml src/

            - name: Run Trivy vulnerability scanner in fs mode
              uses: aquasecurity/trivy-action@0.20.0
              with:
                    scan-type: 'fs'
                    scan-ref: '.'


        
